[package]
name = "first"
version = "0.1.0"
authors = ["pechuga22 <iefaz.santiagovalle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
